trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output build_output'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'app'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appType: 'webApp'
    appName: 'TestPipelinesMS'
    deployToSlotOrASE: true
    resourceGroupName: 'Sandbox'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'